secretsprovider: gcpkms://projects/halo-relay/locations/us-central1/keyRings/halo-pulumi/cryptoKeys/state
encryptedkey: CiQAdv4E5pBOXHCYFwrVBR2Pkyq8itOZAG2oy13jgAY67BLNXF0SSABYrJ1d5x1dHLjSAFNDEA0M2N4Bq78Thl5fqjpac6NEQ/AP3lpDoLfhgtCuWi5DEHpJSrQRsptPKffbT6s5rHAbC/rzTNnI7A==
config:
  gcp:project: halo-relay
  gcp:region: us-west2
  gcp:zone: us-west2-a
  halo-control-plane:controlPlaneImage: us-west2-docker.pkg.dev/halo-relay/halo-west-workspaces/control-plane:0.1.44
  halo-control-plane:workspaceImage: us-west2-docker.pkg.dev/halo-relay/halo-west-workspaces/workspace-server:0.1.44
