import {
  backgroundColor,
  flex,
  focusRing,
  radius,
  shadow,
  spacing,
  text,
} from "maui";
import { style } from "purse-styles";
export const automationStyles = {
  pane: style({
    width: "100%",
    height: "100%",
    overflowY: "auto",
    backgroundColor: backgroundColor.app,
  }),
  content: style(
    flex({ direction: "column", gap: 8 }),
    spacing.padding({ all: 12 }),
    {
      width: "100%",
      maxWidth: "calc(72ch + 48px)",
      marginInline: "auto",
    },
  ),
  titleRow: style(
    flex({ alignItems: "center", justifyContent: "between", gap: 4 }),
  ),
  title: style(text({ size: "xl", fontWeight: 600, color: "highContrast" }), {
    margin: 0,
    minWidth: 0,
    overflowWrap: "anywhere",
  }),
  actions: style(flex({ alignItems: "center", gap: 2 }), { flexShrink: 0 }),
  details: style(text({ size: "sm", color: "lowContrast" }), {
    display: "grid",
    gridTemplateColumns: "max-content 1fr",
    columnGap: spacing.value(6),
    rowGap: spacing.value(1),
    margin: `${spacing.value(6)} 0 0`,
    "& > div": { display: "contents" },
    "& dd": {
      margin: 0,
      minWidth: 0,
      overflowWrap: "anywhere",
      color: "inherit",
    },
    "& dt": { fontWeight: 500 },
  }),
  section: style(flex({ direction: "column", gap: 3 })),
  sectionTitle: style(text({ size: "md", fontWeight: 600 }), { margin: 0 }),
  actionBody: style(text({ size: "sm", color: "highContrast" }), radius.md, {
    margin: 0,
    padding: spacing.value(4),
    backgroundColor: backgroundColor.element,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
  }),
  editor: style(
    text({ size: "sm", color: "highContrast" }),
    radius.md,
    shadow.subtle,
    focusRing("&:focus-visible"),
    {
      width: "100%",
      minHeight: 112,
      padding: spacing.value(4),
      backgroundColor: backgroundColor.element,
      border: 0,
      resize: "vertical",
      fontFamily: "inherit",
    },
  ),
  overlay: style({
    position: "fixed",
    inset: 0,
    zIndex: 100,
    backgroundColor: "rgba(0, 0, 0, 0.35)",
    display: "grid",
    placeItems: "center",
    padding: "24px",
  }),
  modal: style(shadow.strong, radius.lg, spacing.padding({ all: 8 }), {
    width: "min(560px, 100%)",
    maxHeight: "min(720px, calc(100vh - 48px))",
    overflowY: "auto",
    backgroundColor: backgroundColor.app,
    "& [role='dialog']": { outline: "none" },
  }),
  form: style(flex({ direction: "column", gap: 6 })),
  modalHeading: style(text({ size: "md", fontWeight: 600 }), { margin: 0 }),
  label: style(text({ size: "sm" }), flex({ direction: "column", gap: 2 })),
  modalButtons: style(flex({ justifyContent: "end", gap: 3 })),
  list: style({ listStyle: "none", padding: 0, margin: 0 }),
  runLink: style(flex({ direction: "column", gap: 1 }), radius.md, {
    padding: spacing.value(4),
    color: "inherit",
    textDecoration: "none",
    "&:hover": { backgroundColor: backgroundColor.elementHover },
  }),
  runInfo: style(text({ size: "xs", color: "lowContrast" })),
  error: style(text({ size: "sm", color: "highContrast" }), {
    color: "light-dark(#b42318, #ff9592)",
    overflowWrap: "anywhere",
  }),
  empty: style(text({ size: "sm", color: "lowContrast" }), { margin: 0 }),
};
